version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/srv"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 5
    target-branch: "master"
