name: Sync Dependabot updates to other branches

on:
  push:
    branches:
      - main
    paths:
      - '**/package-lock.json'
      - '**/yarn.lock'
      - '.github/dependabot.yml'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge main into dev
        run: |
          git checkout dev
          git merge origin/main --no-edit || echo "No changes to merge"
          git push origin dev
