name: Combinar Dependabot

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  combine-dependabot-prs:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: master
      COMBINE_BRANCH: combine-dependabot
      OUTPUT_JSON: combinado.json

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Configurar Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.13'
#
      #- name: Instalar dependencias
      #  run: pip install requests

      #- name: Ejecutar combine-dependabot.py
      #  run: python combine-dependabot.py
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    #GIT_USERNAME: ${{ github.actor }}
      #    #GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      #    GITHUB_REPOSITORY: ${{ github.repository }}
      #    BASE_BRANCH: ${{ env.TARGET_BRANCH }}
      #    COMBINE_BRANCH: ${{ env.COMBINE_BRANCH }}
      #    PR_USER: dependabot[bot]
      #    OUTPUT_JSON: ${{ env.OUTPUT_JSON }}

      - name: Ejecutar acción de combinación
        uses: clhore/combine-dependabot-pull-requests@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: master
          combine_branch: combine-dependabot
          pr_user: dependabot[bot]
          output_json: combined.json

      - name: Cargar archivo JSON como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: resultado-combinado
          path: combinado.json

      - name: Verificar estado del repositorio antes del merge
        run: |
          echo "Estado del repositorio antes del merge"
          git status
          git log --oneline -n 5

      #- name: Fusionar combine-dependabot en master
      #  run: |
      #    git checkout master
      #    git merge combine-dependabot --no-ff --no-edit
#
      #- name: Verificar estado del repositorio después del merge
      #  run: |
      #    echo "Estado del repositorio después del merge"
      #    git status
      #    git log --oneline -n 5
#
      #- name: Empujar cambios a master
      #  run: |
      #    git push origin master
#
      - name: Verificar archivo combinado
        run: |
          cat $OUTPUT_JSON
