name: Combinar Dependabot

on:
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    env:
      OUTPUT_JSON: combinado.json  # Ruta donde se guardará el archivo JSON
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar combine-dependabot.py
        run: python combine-dependabot.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: debian/master
          COMBINE_BRANCH: combine-dependabot
          BRANCH_PREFIX: dependabot
          OUTPUT_JSON: ${{ env.OUTPUT_JSON }}  # Ruta donde se guardará el archivo JSON}
        
      - name: Check archivo combinado
        run: |
          cat $OUTPUT_JSON
