name: Combinar Dependabot

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  combine:
    runs-on: ubuntu-latest
    env:
      OUTPUT_JSON: combinado.json  # Ruta donde se guardará el archivo JSON

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Configure Git user
        run: |
          git config --global user.email "adria7904@gmail.com"
          git config --global user.name "clhore"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar combine-dependabot.py
        run: python combine-dependabot.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: ${{ github.actor }}
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: master
          COMBINE_BRANCH: combine-dependabot
          BRANCH_PREFIX: dependabot
          OUTPUT_JSON: ${{ env.OUTPUT_JSON }}

      - name: Verificar estado del repositorio antes del merge
        run: |
          echo "Estado del repositorio antes del merge"
          git status
          git log --oneline -n 5

      - name: Fusionar combine-dependabot en master
        run: |
          git checkout master
          git merge combine-dependabot --no-ff --no-edit

      - name: Verificar estado del repositorio después del merge
        run: |
          echo "Estado del repositorio después del merge"
          git status
          git log --oneline -n 5

      - name: Empujar cambios a master
        run: |
          git push origin master

      - name: Verificar archivo combinado
        run: |
          cat $OUTPUT_JSON
